version: '3'
services:
  warrior:
    container_name: warrior
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: [yarn, watch]

volumes:
  node_modules:
